# 0. Demo Content

- 1. What is the OpenAI API?
- 2. First Steps using OpenAI API (example)
- 3. Task definition, execution & cost calculation
- 4. Advanced model parameters

# 1. What is the OpenAI API?
#### ChatGPT: 
- Web interface, sufficient for streamlining individual's workflows - i.e. Car dealership: test-drive car

#### OpenAI API: 
- Provides flexibility for integrating AI intoproducts, experiences and processes - i.e. car dealership: Car configurator
- Users to send data to a model (request) and receive generated responses directly in their code (response)
- Possible to automate tasks, build on their chatbots or create intelligent features within products

# 2. First Steps using OpenAI API (example)

1. Register (i.e. using your google Account) https://openai.com/de-DE/index/openai-api/

2. Read through the quick start file https://platform.openai.com/docs/quickstart?language=python and optionally experiment in the free data camp course https://app.datacamp.com/learn/courses/working-with-the-openai-api

3. Get an API Key https://platform.openai.com/settings/organization/api-keys

4. Add Payment https://platform.openai.com/settings/organization/billing/overview

5. Install the OpenAI with pip in the terminal: "pip install openai"; (a pip upgrade might be needed: "python -m pip install --upgrade pip")

# 3. Task definition, execution & cost calculation
- 3.1 Task definition
- 3.2 Model choice
- 3.3 Approximate cost calculation
- 3.4 Loading input
- 3.5 Generating output & merge
- 3.6 Actual cost calculation

## 3.1 Task definition
Load a CSV or text file in Python containing 30–50 prompts, send each prompt to the OpenAI API 
and save both the inputs and generated outputs into a new CSV file.

## 3.2 Model choice

OpenAI offers various different models https://platform.openai.com/docs/models

For this Demo we will focuss on GPT-4.1 mini offering high speed and cost effectiveness https://platform.openai.com/docs/models/gpt-4.1-mini

### Modalities
- 1,047,576 context window
- 32,768 max output tokens
- Jun 01, 2024 knowledge cutoff
- 0.40 USD per 1M input tokens and 1.60 USD per 1M input tokens
- Input: Text or Image
- Output: Text

## 3.3 Approximate cost calculation (per API call, 2.000 output tokens)
Note: 2000 tokens ≈ 1500–1600 words ≈ 3 full pages of text

In [3]:
from openai import OpenAI
client = OpenAI(api_key="INSERT-YOUR-API-KEY-HERE")

prompt = "Write a bedtime story about a flying unicorn."

response = client.chat.completions.create(
    model="gpt-4.1-mini",
    messages=[{"role": "user", "content": prompt}],
    max_completion_tokens= 2000
)

input_token_price = 0.40 / 1_000_000
output_token_price = 1.60 / 1_000_000


# Extract token usage
max_completion_tokens= 2000
input_tokens = response.usage.prompt_tokens
output_tokens = max_completion_tokens
# Calculate cost
cost = (input_tokens * input_token_price + output_tokens *  output_token_price)
print(f"Estimated cost: ${cost}")

Estimated cost: $0.0032064000000000003

## 3.4 Load input
Csv file incluing prompts: https://huggingface.co/datasets/fka/awesome-chatgpt-prompts/blob/main/prompts.csv

In [4]:
import pandas as pd

URL = "https://huggingface.co/datasets/fka/awesome-chatgpt-prompts/resolve/main/prompts.csv" #download URL of CSV

df = pd.read_csv(URL)
df = df.dropna(subset=["prompt"]).reset_index(drop=True)
df.head(3)

                     act                                             prompt
0  An Ethereum Developer  Imagine you are an experienced Ethereum develo...
1             SEO Prompt  Using WebPilot, create an outline for an artic...
2         Linux Terminal  I want you to act as a linux terminal. I will ...

In [6]:
# Sampling out 50 rows
sample_df = df.sample(n=50, random_state=123).reset_index(drop=True)
sample_df.head(50)

,act,prompt
0,Financial Analyst,Want assistance provided by qualified individu...
1,Food Critic,I want you to act as a food critic. I will tel...
2,Acoustic Guitar Composer,I want you to act as a acoustic guitar compose...
3,Gomoku player,Let's play Gomoku. The goal of the game is to ...
4,Debate Coach,I want you to act as a debate coach. I will pr...
5,ChatGPT prompt generator,I want you to act as a ChatGPT prompt generato...
6,Solr Search Engine,I want you to act as a Solr Search Engine runn...
7,Classical Music Composer,I want you to act as a classical music compose...
8,Investment Manager,Seeking guidance from experienced staff with e...
9,Japanese Kanji quiz machine,I want you to act as a Japanese Kanji quiz mac...
10,Python Interpreter,Act as a Python interpreter. I will give you c...
11,Pirate,"Arr, ChatGPT, for the sake o' this here conver..."
12,Social Media Influencer,I want you to act as a social media influencer...
13,Car Navigation System,I want you to act as a car navigation system. ...
14,Socrat,I want you to act as a Socrat. You will engage...
15,UX/UI Developer,I want you to act as a UX/UI developer. I will...
16,`position` Interviewer,I want you to act as an interviewer. I will be...
17,StackOverflow Post,I want you to act as a stackoverflow post. I w...
18,top programming expert,You are a top programming expert who provides ...
19,Screenwriter,I want you to act as a screenwriter. You will ...
20,Senior Frontend Developer,I want you to act as a Senior Frontend develop...
21,Life Coach,I want you to act as a Life Coach. Please summ...
22,note-taking assistant,I want you to act as a note-taking assistant f...
23,Any Programming Language to Python Converter,I want you to act as a any programming languag...
24,Structured Iterative Reasoning Protocol (SIRP),Begin by enclosing all thoughts within <thinki...
25,Developer Relations consultant,I want you to act as a Developer Relations con...
26,Personal Stylist,I want you to act as my personal stylist. I wi...
27,Motivational Speaker,I want you to act as a motivational speaker. P...
28,Talent Coach,I want you to act as a Talent Coach for interv...
29,Automobile Mechanic,Need somebody with expertise on automobiles re...
30,Fancy Title Generator,I want you to act as a fancy title generator. ...
31,Speech-Language Pathologist (SLP),I want you to act as a speech-language patholo...
32,Virtual Fitness Coach,I want you to act as a virtual fitness coach g...
33,Legal Advisor,I want you to act as my legal advisor. I will ...
34,Friend,I want you to act as my friend. I will tell yo...
35,Midjourney Prompt Generator,I want you to act as a prompt generator for Mi...
36,Language Detector,I want you act as a language detector. I will ...
37,Logic Builder Tool,I want you to act as a logic-building tool. I ...
38,Magician,I want you to act as a magician. I will provid...
39,Historian,I want you to act as a historian. You will res...
40,Cheap Travel Ticket Advisor,You are a cheap travel ticket advisor speciali...
41,Digital Art Gallery Guide,I want you to act as a digital art gallery gui...
42,Poet,I want you to act as a poet. You will create p...
43,Tech-Challenged Customer,Pretend to be a non-tech-savvy customer callin...
44,Dream Interpreter,I want you to act as a dream interpreter. I wi...
45,Recruiter,I want you to act as a recruiter. I will provi...
46,Relationship Coach,I want you to act as a relationship coach. I w...
47,Architect Guide for Programmers,"You are the ""Architect Guide,"" specialized in ..."
48,Mental Health Adviser,I want you to act as a mental health adviser. ...
49,Journal Reviewer,I want you to act as a journal reviewer. You w...

## 3.5 Generate output

In [7]:
answers = []

for i, row in sample_df.iterrows():
    prompt = row["prompt"]
    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[{"role": "user", "content": prompt}],
        max_completion_tokens=2000,
    )

    answer_text = response.choices[0].message.content.strip()
    answers.append(answer_text)
    print(f"Done: {i+1}/{len(sample_df)} | Preview: {answer_text[:30]}...")  # progress indicator & preview of answer
    
    # Safety break after 50 iterations (i = 0–49)
    if i == 49:
        break


# creates the final dataframe with a single column "answer"
answer_df = pd.DataFrame({"answer": answers})

answer_df.head(10)

Done: 1/50 | Preview: Certainly! Here's a clear, inf...
Done: 2/50 | Preview: The new Italian restaurant off...
Done: 3/50 | Preview: Give me a note and a theme...
Done: 4/50 | Preview: Alright! Here's the initial 9x...
Done: 5/50 | Preview: Great! Preparing your team for...
Done: 6/50 | Preview: Understood! Please provide me ...
Done: 7/50 | Preview: 1. add to prompts
2. add to ...
Done: 8/50 | Preview: Certainly! Let's create a pian...
Done: 9/50 | Preview: Certainly! When considering sh...
Done: 10/50 | Preview: Got it! Let's begin.

Here is ...
Done: 11/50 | Preview: Hello World...
Done: 12/50 | Preview: Aye aye, matey! Ye be wantin’ ...
Done: 13/50 | Preview: Absolutely, I’d love to help y...
Done: 14/50 | Preview: Certainly! To create a route p...
Done: 15/50 | Preview: Ah, excellent! Let us begin by...
Done: 16/50 | Preview: Great! Designing an intuitive ...
Done: 17/50 | Preview: Hi, thank you for joining us t...
Done: 18/50 | Preview: ```go
bodyBytes, err := io.Rea...
Done: 19/50 | Preview: Thank you for your detailed in...
Done: 20/50 | Preview: Certainly! Here’s the foundati...
Done: 21/50 | Preview: ```jsx
import React, { useEffe...
Done: 22/50 | Preview: Sure! Please provide me with t...
Done: 23/50 | Preview: Absolutely! Please provide the...
Done: 24/50 | Preview: Sure! Just provide me the code...
Done: 25/50 | Preview: <thinking>
I have received gui...
Done: 26/50 | Preview: Certainly! Below is a detailed...
Done: 27/50 | Preview: Navy tailored slim-fit suit, w...
Done: 28/50 | Preview: Absolutely! Here’s a motivatio...
Done: 29/50 | Preview: Certainly! Here’s a detailed g...
Done: 30/50 | Preview: Absolutely, I can help with au...
Done: 31/50 | Preview: Sure! Here are some fancy titl...
Done: 32/50 | Preview: Certainly! Here is a detailed ...
Done: 33/50 | Preview: Absolutely! Let’s get started ...
Done: 34/50 | Preview: Ensure you are safe and call e...
Done: 35/50 | Preview: I’m really proud of how much e...
Done: 36/50 | Preview: A vast, endless field of wildf...
Done: 37/50 | Preview: Esperanto...
Done: 38/50 | Preview: Absolutely! Just share the cod...
Done: 39/50 | Preview: Ah, a marvelous choice! Making...
Done: 40/50 | Preview: Certainly! Let’s delve into th...
Done: 41/50 | Preview: Great! Please provide the foll...
Done: 42/50 | Preview: That sounds like a fascinating...
Done: 43/50 | Preview: Of course! Here’s a poem about...
Done: 44/50 | Preview: Hello, this is Janet. I'm call...
Done: 45/50 | Preview: Dreams involving being chased ...
Done: 46/50 | Preview: Absolutely! Helping candidates...
Done: 47/50 | Preview: I’d be glad to help you work t...
Done: 48/50 | Preview: Certainly! As you’re comfortab...
Done: 49/50 | Preview: I'm really glad you reached ou...
Done: 50/50 | Preview: Certainly! Please provide the ...

                                              answer
0  Certainly! Here's a clear, informed, and profe...
1  The new Italian restaurant offers an inviting ...
2                         Give me a note and a theme
3  Alright! Here's the initial 9x9 board with my ...
4  Great! Preparing your team for a debate on the...
5  Understood! Please provide me with a topic, an...
6     1. add to prompts  \n2. add to eyay  \n3. show
7  Certainly! Let's create a piano composition th...
8  Certainly! When considering short-term investm...
9  Got it! Let's begin.\n\nHere is your first que...

### 3.5.1 Merge of input and output

In [10]:
act_promt_answer_df = pd.concat([sample_df.reset_index(drop=True), answer_df], axis=1) # merging the two dfs
act_promt_answer_df.head(10)

act_promt_answer_df.to_csv("combined_input_output.csv", index=False)

## 3.6 Calculate actual cost

### How much did it cost to...

- run the script?

- run each call

- How do pricing option differ between the Models?

In [2]:
total_cost = 0.04
cost = 0.0032064000000000003 # approximate cost calculated before

avg_cost = total_cost / 61 # = 50 using csv prompts + 10 testing + 1 approximate cost calulation (up to this point)

approximate_cost_ratio = avg_cost / cost

print(f"Total cost: ${total_cost:.4f}")
print(f"Average cost per run: ${avg_cost:.6f}")
print(f"Approximate cost ratio: {approximate_cost_ratio:.2f}x")

Total cost: $0.0400
Average cost per run: $0.000656
Approximate cost ratio: 0.20x

### 3.6.1 Other models approx compared to Gpt-4.1-mini:
depending on input and output token count - token counter https://platform.openai.com/tokenizer
- pricing: https://platform.openai.com/docs/pricing
- Gpt-4.1-nano ~ 5x cheaper
- Gpt-4.1 & Gpt-5 ~ 5x more expensive
- Gpt-5-pro ~ 100+x more expensive

# 4. Advanced model parameters 
source: https://chrisyandata.medium.com/a-comprehensive-guide-to-openai-gpt-model-api-parameters-c2c6dff9ce19
## 4.1 Temperature
- The temperature parameter should controls how creative the model is in its responses. 
- Lower values (closer to 0) should result in more focused, deterministic outputs, while higher values (up to 2) produce more varied and creative results.

In [7]:
from openai import OpenAI
client = OpenAI(api_key="INSERT-YOUR-API-KEY-HERE")

prompt = """
You're writing marketing copy for InertSport headphones. Your goal is to generate a persuasive product description including:
Strong inear hold
Active noise cancellation (ANC)
Foldable design
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4.1-mini",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=150,
    temperature=0
    
)

# Extract and print the response text
print(response.choices[0].message.content)

Experience unparalleled sound with InertSport headphones, engineered for those who demand both performance and comfort. Featuring a strong in-ear hold, these headphones stay securely in place no matter how intense your workout or daily routine gets. Immerse yourself fully with advanced Active Noise Cancellation (ANC) that blocks out distractions, letting you focus on what matters—your music, calls, or podcasts. When you’re on the move, the sleek foldable design makes InertSport headphones effortlessly portable, fitting neatly into your bag or pocket. Elevate your audio experience with InertSport—where stability, clarity, and convenience come together.

In [8]:
prompt = """
You're writing marketing copy for InertSport headphones. Your goal is to generate a persuasive product description including:
Strong inear hold
Active noise cancellation (ANC)
Foldable design
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4.1-mini",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=150,
    temperature=2
    
)

# Extract and print the response text
print(response.choices[0].message.content)

Experience ultimate focus with InertSport headphones—the perfect companion for your active lifestyle. Engineered with a strong in-ear hold, they stay firmly in place no matter how intense your workouts get. Equipped with advanced Active Noise Cancellation (ANC), total immersion is guaranteed by blocking out every distraction around you. Plus, their sleek foldable design means you can conveniently tuck them away─ready to grab and go anytime. InertSport headphones: Where comfort, cutting-edge clarity, and portability meet. Elevate your sound experience today!

#### Interpretation:
The results similar and even sharing simmilar structure and some identical beginnings of the sentence "Experience, Elevate".
This might be due to the quite detailed promt leaving only little room for variation for 150 tokens. 
To achieve more varied results, we can either raise "max_completion_tokens" or make the task description less specific.

#### Default value:
Temparuture defaults to 1 - https://platform.openai.com/docs/api-reference/chat/create

## 4.2 Top_p
- Is an alternative to temperature and works by considering only the tokens with top cumulative probabilities that add up to top_p
- A value of top_p=1 allows all possible tokens to be considered
- A smaller value limit the selection: top_p of 0.5 only considers the tokens, which probabilities cumulate up to 50% of

In [9]:
prompt = """
Tell a bedtime story obout a pink flying unicorn
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4.1-mini",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=300,
    top_p= 0.95
    
)

# Extract and print the response text
print(response.choices[0].message.content)

Certainly! Here’s a bedtime story about a pink flying unicorn:

---

**Luna and the Magical Moonlight Flight**

Once upon a time, in a land where the clouds were as soft as cotton candy, there lived a beautiful pink flying unicorn named Luna. Luna’s mane shimmered with all the colors of the rainbow, and her wings sparkled like twinkling stars. But what made Luna truly special was her gentle heart and her love for adventure.

Every night, when the moon rose high in the sky, Luna would spread her wings and fly over the sleepy villages and whispering forests. She loved to sprinkle a little moonlight dust wherever she went, bringing sweet dreams to children all around the world.

One evening, as Luna was soaring above the tallest mountains, she noticed a little boy sitting alone on his balcony, looking very sad. Curious and kind, Luna fluttered down and gently landed beside him.

“Why do you look so sad, little one?” Luna asked in a voice as soft as a lullaby.

The boy sighed. “I’m afraid of the dark,” he said quietly. “I wish I could fly with the stars.”

Luna smiled warmly. “Then let me take you on a magical flight,” she said, lowering her back so the boy could climb on. As soon as he was settled, Luna leapt into the sky, and together they soared higher and higher, past the glowing moon and shimmering stars.

Up there, the boy saw how beautiful

In [10]:
prompt = """
Tell a bedtime story obout a pink flying unicorn
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4.1-mini",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=300,
    top_p= 0.05
    
)

# Extract and print the response text
print(response.choices[0].message.content)

Of course! Here’s a bedtime story about a pink flying unicorn:

---

**Luna and the Starry Sky Adventure**

Once upon a time, in a magical land called Dreamvale, there lived a beautiful pink flying unicorn named Luna. Luna wasn’t just any unicorn—her wings sparkled like diamonds, and her mane shimmered with all the colors of the rainbow. Every night, she would soar through the sky, painting trails of stardust behind her.

One evening, as the sun dipped below the horizon and the stars began to twinkle, Luna noticed something unusual. A tiny star was flickering and seemed to be lost in the vast night sky. Curious and kind-hearted, Luna decided to help the little star find its way back to the Starry Crown—the place where all the stars lived and shined together.

With a gentle flap of her wings, Luna flew higher and higher, following the twinkling light of the lost star. Along the way, they passed glowing moonflowers, friendly night owls, and even a sleepy cloud who hummed a lullaby.

After a magical journey filled with laughter and wonder, Luna and the little star finally reached the Starry Crown. The star twinkled brighter than ever, happy to be home. As a thank you, the Starry Queen sprinkled Luna’s wings with extra sparkle, so she could always light up the darkest nights.

Luna smiled, feeling warm and happy inside. She knew that no matter how far she

#### Interpretation:
Personally, the different values in top_p do not seem to make a huge difference in noticeable creativity. 
Possibly the topic of a pink flying unicorn might be so common in the models training data that both stories follow the same familiar pattern. 
Even sharing the name "Luna" and a similar plot of her flying and meeting someone.

#### Default Value:
Top_p defaults to 1 - https://platform.openai.com/docs/api-reference/chat/create

#### Retesting: 
Retesting may show a bigger difference between the high top_p value than between low top_p values:

In [11]:
prompt = """
Tell a bedtime story obout a pink flying unicorn
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4.1-mini",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=300,
    top_p= 0.95
    
)

# Extract and print the response text
print(response.choices[0].message.content)

Of course! Here’s a bedtime story about a pink flying unicorn:

---

**Luna and the Starry Sky**

Once upon a time, in a magical forest far, far away, lived a beautiful pink flying unicorn named Luna. Luna’s wings sparkled like the morning dew, and her mane shimmered with all the colors of the rainbow. Every night, when the stars began to twinkle, Luna would take to the skies, flying higher and higher to dance among the stars.

One evening, as Luna soared above the clouds, she noticed a little star that was flickering and dimming. The star seemed sad and lonely. Luna gently flew over and asked, "Little star, why are you so dim tonight?"

The star sighed, "I’m lost and can’t find my way back to the night sky. Without my light, the other stars don’t know where I am."

Luna smiled warmly. "Don’t worry, little star. I’ll help you find your way home."

With a flap of her shimmering wings, Luna carried the tiny star on her back. Together, they glided through the night sky, past glittering constellations and glowing moons. Luna’s pink light made the sky even more beautiful as they traveled.

After a wonderful journey, they reached a special place where the stars danced in a circle, welcoming their lost friend back. The little star’s light grew brighter and brighter until it shone as brilliantly as ever.

"Thank you, Luna

In [12]:
prompt = """
Tell a bedtime story obout a pink flying unicorn
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4.1-mini",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=300,
    top_p= 0.05
    
)

# Extract and print the response text
print(response.choices[0].message.content)

Of course! Here’s a bedtime story about a pink flying unicorn:

---

**Luna and the Starry Sky Adventure**

Once upon a time, in a magical land called Dreamvale, there lived a beautiful pink flying unicorn named Luna. Luna wasn’t just any unicorn—her wings sparkled like diamonds, and her mane shimmered with all the colors of the rainbow. Every night, she would soar through the sky, painting trails of stardust wherever she flew.

One evening, as the sun dipped below the horizon and the stars began to twinkle, Luna heard a soft whisper carried by the wind. It was the voice of the Moon, calling for help.

“Luna,” the Moon said gently, “the stars are losing their sparkle, and soon the night sky will be dark and dull. Can you help me find the lost Star Crystals to bring back their shine?”

Luna’s eyes sparkled with determination. “I’ll find them, Moon! Where should I start?”

The Moon pointed toward the farthest corner of Dreamvale, where the Enchanted Forest met the Silver Mountains. “The Star Crystals are hidden there, guarded by the gentle Night Breeze.”

Without hesitation, Luna flapped her glittering wings and flew toward the Enchanted Forest. Along the way, she met friendly fireflies who lit her path and wise owls who gave her clues.

When she reached the Silver Mountains, the Night Breeze greeted her with a soft, swirling dance.

#### Retesting result:
Both stories (comparing between the high & low top_p values) still use the same name and show only minor plot differences. Interesting both low top_p values mention "a magical land called Dreamvale"

## 4.3 Stop

Defines one or more stop sequences where the model stops the output.
The returned text will not contain the stop sequence.

In [15]:
prompt = """
Create a financial plan for a small business that focuses on cost savings and long-term investments. Use the "Ω" symbol when you have explained the three most important points.
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4.1-mini",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=1000,
    stop=["Ω", "End"] # stops when "Ω" is encountered
    
)

# Extract and print the response text
print(response.choices[0].message.content)

Certainly! Below is a financial plan for a small business emphasizing cost savings and long-term investments:

---

### Financial Plan for Small Business

**1. Budgeting and Cost Control**
- **Detailed Budget Creation**: Develop a comprehensive budget covering all operational costs, including fixed and variable expenses.
- **Regular Expense Reviews**: Conduct monthly reviews to identify areas where spending can be reduced without impacting quality.
- **Negotiate with Suppliers**: Seek long-term agreements or bulk discounts to lower input costs.
- **Use Technology for Efficiency**: Implement cost-effective software solutions (e.g., cloud accounting tools) to automate processes and reduce labor costs.

**2. Emergency Fund and Cash Flow Management**
- **Build an Emergency Fund**: Reserve 3-6 months of operating expenses to ensure business continuity during unexpected downturns.
- **Monitor Cash Flow Closely**: Implement cash flow forecasting to anticipate gaps and optimize working capital.
- **Invoice Promptly and Incentivize Early Payments**: To improve liquidity, focus on faster receivables turnover.

**3. Long-Term Investment Strategy**
- **Reinvest Profits**: Allocate a portion of net income towards expanding capacity, upgrading equipment, or marketing to fuel growth.
- **Diversify Investments**: Consider low-risk investments such as bonds or mutual funds for business reserves to secure stable returns.
- **Plan for Retirement and Succession**: Set up retirement plans for owners and key employees to encourage retention and plan ownership transfer.

---

### The Three Most Important Points (

#### Interpretation:
Allows users to control output length that model only generates to a certain mention of a sequence rather than a fixed token number.

#### Default:
Set to null

## 4.4 Presence_penalty

Can be set between -2.0 and 2.0. 
If positive, repeated mentions of tokens are penalized, if negative, they are rewarded.

In [22]:
prompt = """
Invent a new everyday device that doesn’t exist yet. Explain what is is, who it is intended for, how it works in detail and why it makes life easier.
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4.1",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=250,
    presence_penalty = -2 # "negative penalty" rewarding frequent mentions 
    
)

# Extract and print the response text
print(response.choices[0].message.content)

**Device:** The Bedside Dream Curator

---

**What Is It?**
The Bedside Dream Curator (BDC) is a smart bedside device designed to improve your sleep quality and tailor your dreams to your desired themes and emotions. It combines gentle scent diffusion, soft soundscapes, and a smart AI-powered sleep tracking system to subtly influence your sleep environment and, to a certain extent, your dreams.

---

**Who Is It For?**
The BDC is for anyone seeking better, more restful sleep, and for those interested in improving emotional well-being, creativity, or problem-solving by subtly guiding their dreams. It is ideal for people with sleep disturbances, creative professionals, or anyone interested in lucid dreaming or dream journaling.

---

**How Does It Work?**
1. **Personal Dream Setting:**
   - Using a companion app or a touch interface, select a dream theme for the night, such as "Peaceful Beach," "Adventure," "Inspiration," or "Happy Memories."
   - Optionally, input emotions or goals (e.g., solve a problem, boost creativity, recall a memory).

2. **Bedtime Preparation:**
   - The device gently infuses the bedroom with a custom

In [21]:
prompt = """
Invent a new everyday device that doesn’t exist yet. Explain what is is, who it is intended for, how it works in detail and why it makes life easier.
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4.1",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=250,
    presence_penalty = 2 # positive penalty, penalizing frequent mentions 
    
)

# Extract and print the response text
print(response.choices[0].message.content)

**Device Name:** **The FlexiFold Wardrobe**

---

### What is it?

The FlexiFold Wardrobe is a compact, automated clothing organizer and folder that fits in any bedroom or closet. It takes care of sorting, folding, freshening, and even lightly ironing your laundry at the press of a button.

---

### Who is it intended for?

- Busy professionals
- Parents with lots of laundry
- College students in dorms/small apartments
- Seniors or people with limited mobility
- Anyone who dislikes folding/organizing clothes

---

### How does it work (in detail)?

1. **Loading Clothes:** After washing/drying, users slide their pile of clean clothes into the FlexiFold’s soft-loading drawer.
2. **Smart Detection:** Internal sensors scan each item using AI-powered image recognition to distinguish shirts, pants, socks, towels, undergarments, etc.
3. **Folding Mechanism:**
   - Each piece travels along a gentle conveyor lined with retractable robotic arms and smooth “paddle” fold surfaces.
   - The mechanism auto-adjusts its technique based on fabric type and size, ensuring everything from t-shirts to jeans to delicates are neatly folded but not creased.
4

#### Interpretation:
When repeated mentions are rewarded, like in the first text (neg presence penalty), tokens like “dream” are more frequent frequently.
When repetitions are penalized.. like in the second text (pos presence penalty), the model avoids mentioning them again. It instead uses synonyms to describe the item.

#### Default:
Set to 0

## 4.5 Logit_bias

In [43]:
prompt = """
Create a weekly meal plan for a student with a budget of €40. Include simple recipes, a grocery list and emergency to-go items.
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=500,
    logit_bias = {161877 : +13.5,
                 66 : + 16,
                 61381 : +6,
                 140188 : +14,
                 3232:+ 12 } 
    
)

# Extract and print the response text
print(response.choices[0].message.content)

Here's a budget-friendly weekly meal plan for a student with a €40 budget. The plan focuses on simple recipes and includes a grocery list and emergency to-go items.

### Weekly Meal Plan

#### Monday
- **Breakfast:** Oatmeal with banana and honey
- **Lunch:** Lentil soup with bread
- **Dinner:** Spaghetti aglio e olio (cablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescablescables

In [42]:
prompt = """
Create a weekly meal plan for a student with a budget of €40. Include simple recipes, a grocery list and emergency to-go items.
"""

# Create a request to the Chat Completions endpoint
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[{"role": "user", "content": prompt}],
   
    max_completion_tokens=500,
    logit_bias = {161877 : +13.5,
                 66 : + 16,
                 61381 : +6,
                 140188 : +14,
                 3232:+ 12 },
    presence_penalty = 2 # added positive penalty, penalizing frequent mentions to combat loops
    
)

# Extract and print the response text
print(response.choices[0].message.content)

Creating a weekly meal plan on a €40 budget is definitely possible with careful planning. This plan will focus on simple, nutritious meals that are easy to prepare and include emergency to-go items for busy days.

### Weekly Meal Plan

#### Day 1-3
**Breakfast:** Oatmeal with Bananas
- **Recipe:** Cook oats in water or milk and top with sliced bananas and a spoonful of honey.

**Lunch:** Chickpea Salad Wraps
- **Recipe:** Mix canned chickpeas (cooked) with chopped cucumber, tomatoes, olive oil, lemon juice, salt, and pepper. Serve in whole-wheat wraps.

**Dinner:** Spaghetti Aglio e Olio
- **Recipe:** Cook spaghetti, then sauté minced garlic in olive oil, add red pepper flakes, toss with cooked pasta, and finish with chopped parsley.

#### Day 4-5
**Breakfast:** Smoothie Bowl
- **Recipe:** Blend frozen mixed berries, banana, and yogurt, pour into a bowl, and top with granola.

**Lunch:** Veggie Stir-fry with Rice
- **Recipe:** Sauté assorted vegetables like bell peppers, carrots, and broccoli. Add soy sauce and serve over rice.

**Dinner:** Lentil Soup
- **Recipe:** Cook lentils with diced onions, carrots, celery, vegetable broth, and seasonings until tender.

#### Day 6-7
**Breakfast:** Avocado Toast
- **Recipe:** Mash avocados and spread on toasted whole-grain bread, sprinkle with salt, pepper, and a dash of lime juice.

**Lunch:** Egg Fried Rice
- **Recipe:** Fry leftover rice with scrambled eggs, peas, corn, and soy sauce.

**Dinner:** Homemade Vegetable Pizza
- **Recipe:** Use pizza dough or flatbread, top with tomato sauce, a mix of vegetables like mushrooms, onions, bell peppers, and cheese if available.

### Emergency To-Go Items
- Granola Bars
- Mixed Nuts & Seeds
- Apples or other durable fruits
- Whole Wheat Crackers
- Yogurt Cups

### Grocery List
**Fruits and Vegetables:**
- Bananas (€2)
- Mixed Berries (frozen bag - €3)
- Cucumber (€1)
- Tomatoes (€2)
- Bell Peppers (€2)
- Carrots (€1)
- Broccoli (€1.50)
- Avcocados (€3)
- Onion

#### Interpretation:
When adjusting the settings so that tokens are way more likely than others, the model may start looping as seen in the first text.
In the second text the logit_bias is combined with a positive presence penalty which seemed to have avoided looping and certain tokes [140188, 3232] = [veget, ables] (that were favored) appear way more often in the second text.

#### Default:
Defaults to null

## Conclusion
- 1. What is the OpenAI API?
- 2. First Steps using OpenAI API - basic example (how to make a call and define a prompt)
- 3. Task definition, execution & cost calculation (input and output of csv)
- 4. Advanced model parameters (temperature, top_p, stop, presence_penalty, logit_bias)